In [8]:
# NumPy 2 e necessario para ler os pickles gerados pela limpeza.
%pip install pandas "numpy>=2,<3" nltk scikit-learn "gensim>=4.4" transformers torch
# Apos atualizar pacotes, reinicie o kernel antes de executar as proximas celulas.

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.0.6)
Requirement already satisfied: numpy<3,>=2 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.5.3)
Requirement already satisfied: nltk in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.10.3)
Requirement already satisfied: scikit-learn in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.5.0)
Requirement already satisfied: gensim>=4.4 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (4.4.0)
Requirement already satisfied: transformers in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (5.17.0)
Requirement already satisfied: torch in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.14.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2026.4)
Requirement already satisfied: defusedxml in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nltk) (2026.9.10)
Requirement already satisfied: tqdm in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nltk) (4.70.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from gensim>=4.4) (8.0.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers) (1.32.0)
Requirement already satisfied: packaging>=20.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers) (6.0.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers) (0.23.2)
Requirement already satisfied: typer in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers) (0.8.0)
Requirement already satisfied: filelock in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch) (4.0.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch) (82.0.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch) (3.7)
Requirement already satisfied: jinja2 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch) (2026.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: six>=1.5 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: wrapt in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from smart_open>=1.8.1->gensim>=4.4) (2.2.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tqdm->nltk) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: anyio in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.15.1)
Requirement already satisfied: certifi in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\berna\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\berna\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [9]:
# No Windows, carregue o PyTorch antes de pandas, NLTK e Gensim.
# Reinicie o kernel antes de executar esta celula se houve falha de DLL.
try:
    import torch
except OSError as erro:
    if getattr(erro, 'winerror', None) == 1114:
        raise RuntimeError(
            'Falha ao inicializar as DLLs do PyTorch. Reinicie o kernel e '
            'execute o notebook desde o inicio para carregar torch primeiro.'
        ) from erro
    raise

from pathlib import Path
import pandas as pd
import numpy as np
from IPython.display import display

if int(np.__version__.split(".")[0]) < 2:
    raise RuntimeError("Execute a instalacao de NumPy >= 2 na primeira celula e reinicie o kernel antes de ler o pickle.")

raiz_projeto = next(
    (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
     if (p / '_DadosLimpos').is_dir()), None
)
if raiz_projeto is None:
    raise RuntimeError('Execute o notebook dentro do repositorio PLN_SteamRecommend.')
caminho_dados = raiz_projeto / '_DadosLimpos' / 'jogos_steam.pkl.gz'
df = pd.read_pickle(caminho_dados)
colunas_esperadas = {
    'appid', 'name', 'genres', 'description',
    'description_idioma', 'description_tokens_sem_stopwords',
}
colunas_ausentes = colunas_esperadas - set(df.columns)
if colunas_ausentes:
    raise ValueError(f'Reexecute a limpeza; faltam as colunas: {sorted(colunas_ausentes)}')
if not df['description_idioma'].eq('en').all():
    raise ValueError('Reexecute a limpeza com o filtro de ingles antes da busca.')
if df.empty:
    raise ValueError('O catalogo limpo esta vazio.')
if not df['description_tokens_sem_stopwords'].map(lambda tokens: isinstance(tokens, list)).all():
    raise ValueError('Os tokens devem ser listas preservadas pelo pickle da limpeza.')

# A posicao de cada jogo sera a mesma em todas as matrizes de embeddings.
df = df.reset_index(drop=True)
print(f'Jogos Steam disponiveis para busca: {len(df):,}')
df[['appid', 'name', 'genres', 'description']].head()

Jogos Steam disponiveis para busca: 178,720

,appid,name,genres,description
0,10,Counter-Strike,Action,Play the world s number 1 online action game E...
1,20,Team Fortress Classic,Action,One of the most popular online action games of...
2,30,Day of Defeat,Action,Enlist in an intense brand of Axis vs Allied t...
3,40,Deathmatch Classic,Action,Enjoy fast paced multiplayer gaming with Death...
4,50,Half-Life: Opposing Force,Action,Return to the Black Mesa Research Facility as ...

In [10]:
import unicodedata
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import TweetTokenizer

try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords', raise_on_error=True)

# Mesmas etapas da limpeza para representar as consultas em ingles.
tokenizador = TweetTokenizer(preserve_case=True, reduce_len=False, strip_handles=False)
apostrofos = str.maketrans({'\u2018': "'", '\u2019': "'", '\u02bc': "'"})

def tokenizar(texto):
    return tokenizador.tokenize(texto)

def normalizar(tokens):
    return [
        unicodedata.normalize(
            'NFKC', unicodedata.normalize('NFKC', token).translate(apostrofos).lower()
        ) for token in tokens
    ]

negacoes = {'no', 'not', 'nor', 'never', 'neither', 'nothing', 'nobody', 'without', 'cannot', "n't"}
stopwords_en = {
    palavra for palavra in normalizar(stopwords.words('english'))
    if palavra not in negacoes and not palavra.endswith("n't")
}

def remover_stopwords(tokens):
    return [token for token in tokens if token not in stopwords_en]

# Reutiliza as listas ja preparadas; nao tokeniza o catalogo novamente.
df['tokens_sem_stopwords'] = df['description_tokens_sem_stopwords']
df[['appid', 'name', 'tokens_sem_stopwords']].head()

,appid,name,tokens_sem_stopwords
0,10,Counter-Strike,"[play, world, number, 1, online, action, game,..."
1,20,Team Fortress Classic,"[one, popular, online, action, games, time, te..."
2,30,Day of Defeat,"[enlist, intense, brand, axis, vs, allied, tea..."
3,40,Deathmatch Classic,"[enjoy, fast, paced, multiplayer, gaming, deat..."
4,50,Half-Life: Opposing Force,"[return, black, mesa, research, facility, one,..."

# Representação 1 - Word2Vec

In [11]:
from gensim.models import Word2Vec

# Treinar Word2Vec nas descricoes dos jogos Steam.
modelo_w2v = Word2Vec(
    sentences=df["tokens_sem_stopwords"].tolist(),
    vector_size=190,
    window=5,
    min_count=1,
    sg=1,          # Skip-gram
    seed=42,
    workers=1,     # ajuda na reprodutibilidade
    epochs=10
)

print("Tamanho do vocabulário:", len(modelo_w2v.wv))
print("Dimensões dos vetores:", modelo_w2v.vector_size)

# Algumas palavras disponíveis no vocabulário
list(modelo_w2v.wv.index_to_key)[:20]

Tamanho do vocabulário: 97647
Dimensões dos vetores: 190

['game',
 'world',
 'adventure',
 'play',
 'explore',
 'action',
 'new',
 'build',
 'time',
 'based',
 'find',
 'fight',
 'way',
 'one',
 'survive',
 'puzzle',
 'every',
 'story',
 'players',
 'enemies']

In [12]:
import numpy as np

def vetor_documento_word2vec(tokens):
    # Calcula a média dos vetores Word2Vec das palavras conhecidas.
    vetores = [
        modelo_w2v.wv[token]
        for token in tokens
        if token in modelo_w2v.wv
    ]

    if not vetores:
        return np.zeros(
            modelo_w2v.vector_size,
            dtype=np.float32
        )

    return np.mean(vetores, axis=0)


# Criar uma matriz: uma linha por descrição
embeddings_word2vec = np.vstack(
    df["tokens_sem_stopwords"].apply(
        vetor_documento_word2vec
    )
)

# DataFrame apenas para inspecionar a representação
df_word2vec = pd.DataFrame(
    embeddings_word2vec,
    columns=[
        f"w2v_{i:03d}"
        for i in range(
            embeddings_word2vec.shape[1]
        )
    ]
)

df_word2vec.insert(
    0,
    "appid",
    df["appid"].values
)

print(
    "Formato da matriz Word2Vec:",
    embeddings_word2vec.shape
)

# Mostrar somente algumas dimensões
df_word2vec.iloc[:5, :8]

Formato da matriz Word2Vec: (178720, 190)

   appid   w2v_000   w2v_001   w2v_002   w2v_003   w2v_004   w2v_005   w2v_006
0     10  0.204895  0.117850  0.073719 -0.026350 -0.137101  0.329192 -0.151584
1     20  0.116498  0.109501  0.106506 -0.046189 -0.057746  0.317678 -0.155836
2     30  0.155569  0.057073 -0.018256 -0.138521  0.020948  0.321817 -0.237794
3     40  0.232176  0.210333  0.145649  0.000174 -0.109954  0.267099 -0.455526
4     50  0.177997  0.094175  0.039929  0.031535 -0.096041  0.255905 -0.200020

# Representacao 2 - BERT em ingles

Usa `google-bert/bert-base-uncased` com media dos tokens (mean pooling). O primeiro carregamento baixa os pesos do modelo. O processamento do catalogo inteiro pode demorar, principalmente em CPU. Este BERT nao foi ajustado especificamente para similaridade de frases; compare os resultados com Word2Vec.

In [13]:
import torch

from transformers import AutoTokenizer, AutoModel

MODELO_BERT = "google-bert/bert-base-uncased"

# Detectar automaticamente GPU, quando disponível
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Dispositivo:", device)

# Carregar tokenizador e modelo
tokenizer_bert = AutoTokenizer.from_pretrained(
    MODELO_BERT,
    do_lower_case=True
)

modelo_bert = AutoModel.from_pretrained(
    MODELO_BERT
)

modelo_bert = modelo_bert.to(device)
modelo_bert.eval()

print("Modelo carregado:", MODELO_BERT)

Dispositivo: cpu

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 812.85it/s]
[transformers] BertModel LOAD REPORT from: google-bert/bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Modelo carregado: google-bert/bert-base-uncased

In [14]:
def mean_pooling(
    last_hidden_state,
    attention_mask
):
    # Calcula a média dos vetores dos tokens,
    # ignorando posições utilizadas apenas como padding.
    mascara = attention_mask.unsqueeze(-1).expand(
        last_hidden_state.size()
    ).float()

    soma = torch.sum(
        last_hidden_state * mascara,
        dim=1
    )

    quantidade = torch.clamp(
        mascara.sum(dim=1),
        min=1e-9
    )

    return soma / quantidade


def gerar_embeddings_bert(
    textos,
    batch_size=8
):
    # Gera um vetor por texto usando
    # BERT em ingles + mean pooling.
    todos_embeddings = np.empty((len(textos), modelo_bert.config.hidden_size), dtype=np.float32)

    for inicio in range(
        0,
        len(textos),
        batch_size
    ):
        lote = textos[
            inicio:inicio + batch_size
        ]

        entradas = tokenizer_bert(
            lote,
            padding=True,
            truncation=True,
            max_length=128,
            return_tensors="pt"
        )

        entradas = {
            chave: valor.to(device)
            for chave, valor
            in entradas.items()
        }

        with torch.no_grad():
            saida = modelo_bert(**entradas)

        embeddings_lote = mean_pooling(
            saida.last_hidden_state,
            entradas["attention_mask"]
        )

        todos_embeddings[inicio:inicio + len(lote)] = embeddings_lote.cpu().numpy()
        if inicio == 0 or (inicio // batch_size + 1) % 100 == 0 or inicio + len(lote) == len(textos):
            print(f'BERT: {inicio + len(lote):,}/{len(textos):,} descricoes', flush=True)

    return todos_embeddings


# Usamos a descricao limpa em ingles, preservando stopwords e contexto.
textos = df["description"].tolist()

embeddings_bert = gerar_embeddings_bert(
    textos
)

print(
    "Formato da matriz BERT:",
    embeddings_bert.shape
)

BERT: 8/178,720 descricoes
BERT: 800/178,720 descricoes
BERT: 1,600/178,720 descricoes
BERT: 2,400/178,720 descricoes
BERT: 3,200/178,720 descricoes
BERT: 4,000/178,720 descricoes
BERT: 4,800/178,720 descricoes
BERT: 5,600/178,720 descricoes
BERT: 6,400/178,720 descricoes
BERT: 7,200/178,720 descricoes
BERT: 8,000/178,720 descricoes
BERT: 8,800/178,720 descricoes
BERT: 9,600/178,720 descricoes
BERT: 10,400/178,720 descricoes
BERT: 11,200/178,720 descricoes
BERT: 12,000/178,720 descricoes
BERT: 12,800/178,720 descricoes
BERT: 13,600/178,720 descricoes
BERT: 14,400/178,720 descricoes
BERT: 15,200/178,720 descricoes
BERT: 16,000/178,720 descricoes
BERT: 16,800/178,720 descricoes
BERT: 17,600/178,720 descricoes
BERT: 18,400/178,720 descricoes
BERT: 19,200/178,720 descricoes
BERT: 20,000/178,720 descricoes
BERT: 20,800/178,720 descricoes
BERT: 21,600/178,720 descricoes
BERT: 22,400/178,720 descricoes
BERT: 23,200/178,720 descricoes
BERT: 24,000/178,720 descricoes
BERT: 24,800/178,720 descricoes
BERT: 25,600/178,720 descricoes
BERT: 26,400/178,720 descricoes
BERT: 27,200/178,720 descricoes
BERT: 28,000/178,720 descricoes
BERT: 28,800/178,720 descricoes
BERT: 29,600/178,720 descricoes
BERT: 30,400/178,720 descricoes
BERT: 31,200/178,720 descricoes
BERT: 32,000/178,720 descricoes
BERT: 32,800/178,720 descricoes
BERT: 33,600/178,720 descricoes
BERT: 34,400/178,720 descricoes
BERT: 35,200/178,720 descricoes
BERT: 36,000/178,720 descricoes
BERT: 36,800/178,720 descricoes
BERT: 37,600/178,720 descricoes
BERT: 38,400/178,720 descricoes
BERT: 39,200/178,720 descricoes
BERT: 40,000/178,720 descricoes
BERT: 40,800/178,720 descricoes
BERT: 41,600/178,720 descricoes
BERT: 42,400/178,720 descricoes
BERT: 43,200/178,720 descricoes
BERT: 44,000/178,720 descricoes
BERT: 44,800/178,720 descricoes
BERT: 45,600/178,720 descricoes
BERT: 46,400/178,720 descricoes
BERT: 47,200/178,720 descricoes
BERT: 48,000/178,720 descricoes
BERT: 48,800/178,720 descricoes
BERT: 49,600/178,720 descricoes
BERT: 50,400/178,720 descricoes
BERT: 51,200/178,720 descricoes
BERT: 52,000/178,720 descricoes
BERT: 52,800/178,720 descricoes
BERT: 53,600/178,720 descricoes
BERT: 54,400/178,720 descricoes
BERT: 55,200/178,720 descricoes
BERT: 56,000/178,720 descricoes
BERT: 56,800/178,720 descricoes
BERT: 57,600/178,720 descricoes
BERT: 58,400/178,720 descricoes
BERT: 59,200/178,720 descricoes
BERT: 60,000/178,720 descricoes
BERT: 60,800/178,720 descricoes
BERT: 61,600/178,720 descricoes
BERT: 62,400/178,720 descricoes
BERT: 63,200/178,720 descricoes
BERT: 64,000/178,720 descricoes
BERT: 64,800/178,720 descricoes
BERT: 65,600/178,720 descricoes
BERT: 66,400/178,720 descricoes
BERT: 67,200/178,720 descricoes
BERT: 68,000/178,720 descricoes
BERT: 68,800/178,720 descricoes
BERT: 69,600/178,720 descricoes
BERT: 70,400/178,720 descricoes
BERT: 71,200/178,720 descricoes
BERT: 72,000/178,720 descricoes
BERT: 72,800/178,720 descricoes
BERT: 73,600/178,720 descricoes
BERT: 74,400/178,720 descricoes
BERT: 75,200/178,720 descricoes
BERT: 76,000/178,720 descricoes
BERT: 76,800/178,720 descricoes
BERT: 77,600/178,720 descricoes
BERT: 78,400/178,720 descricoes
BERT: 79,200/178,720 descricoes
BERT: 80,000/178,720 descricoes
BERT: 80,800/178,720 descricoes
BERT: 81,600/178,720 descricoes
BERT: 82,400/178,720 descricoes
BERT: 83,200/178,720 descricoes
BERT: 84,000/178,720 descricoes
BERT: 84,800/178,720 descricoes
BERT: 85,600/178,720 descricoes
BERT: 86,400/178,720 descricoes
BERT: 87,200/178,720 descricoes
BERT: 88,000/178,720 descricoes
BERT: 88,800/178,720 descricoes
BERT: 89,600/178,720 descricoes
BERT: 90,400/178,720 descricoes
BERT: 91,200/178,720 descricoes
BERT: 92,000/178,720 descricoes
BERT: 92,800/178,720 descricoes
BERT: 93,600/178,720 descricoes
BERT: 94,400/178,720 descricoes
BERT: 95,200/178,720 descricoes
BERT: 96,000/178,720 descricoes
BERT: 96,800/178,720 descricoes
BERT: 97,600/178,720 descricoes
BERT: 98,400/178,720 descricoes
BERT: 99,200/178,720 descricoes
BERT: 100,000/178,720 descricoes
BERT: 100,800/178,720 descricoes
BERT: 101,600/178,720 descricoes
BERT: 102,400/178,720 descricoes
BERT: 103,200/178,720 descricoes
BERT: 104,000/178,720 descricoes
BERT: 104,800/178,720 descricoes
BERT: 105,600/178,720 descricoes
BERT: 106,400/178,720 descricoes
BERT: 107,200/178,720 descricoes
BERT: 108,000/178,720 descricoes
BERT: 108,800/178,720 descricoes
BERT: 109,600/178,720 descricoes
BERT: 110,400/178,720 descricoes
BERT: 111,200/178,720 descricoes
BERT: 112,000/178,720 descricoes
BERT: 112,800/178,720 descricoes
BERT: 113,600/178,720 descricoes
BERT: 114,400/178,720 descricoes
BERT: 115,200/178,720 descricoes
BERT: 116,000/178,720 descricoes
BERT: 116,800/178,720 descricoes
BERT: 117,600/178,720 descricoes
BERT: 118,400/178,720 descricoes
BERT: 119,200/178,720 descricoes
BERT: 120,000/178,720 descricoes
BERT: 120,800/178,720 descricoes
BERT: 121,600/178,720 descricoes
BERT: 122,400/178,720 descricoes
BERT: 123,200/178,720 descricoes
BERT: 124,000/178,720 descricoes
BERT: 124,800/178,720 descricoes
BERT: 125,600/178,720 descricoes
BERT: 126,400/178,720 descricoes
BERT: 127,200/178,720 descricoes
BERT: 128,000/178,720 descricoes
BERT: 128,800/178,720 descricoes
BERT: 129,600/178,720 descricoes
BERT: 130,400/178,720 descricoes
BERT: 131,200/178,720 descricoes
BERT: 132,000/178,720 descricoes
BERT: 132,800/178,720 descricoes
BERT: 133,600/178,720 descricoes
BERT: 134,400/178,720 descricoes
BERT: 135,200/178,720 descricoes
BERT: 136,000/178,720 descricoes
BERT: 136,800/178,720 descricoes
BERT: 137,600/178,720 descricoes
BERT: 138,400/178,720 descricoes
BERT: 139,200/178,720 descricoes
BERT: 140,000/178,720 descricoes
BERT: 140,800/178,720 descricoes
BERT: 141,600/178,720 descricoes
BERT: 142,400/178,720 descricoes
BERT: 143,200/178,720 descricoes
BERT: 144,000/178,720 descricoes
BERT: 144,800/178,720 descricoes
BERT: 145,600/178,720 descricoes
BERT: 146,400/178,720 descricoes
BERT: 147,200/178,720 descricoes
BERT: 148,000/178,720 descricoes
BERT: 148,800/178,720 descricoes
BERT: 149,600/178,720 descricoes
BERT: 150,400/178,720 descricoes
BERT: 151,200/178,720 descricoes
BERT: 152,000/178,720 descricoes
BERT: 152,800/178,720 descricoes
BERT: 153,600/178,720 descricoes
BERT: 154,400/178,720 descricoes
BERT: 155,200/178,720 descricoes
BERT: 156,000/178,720 descricoes
BERT: 156,800/178,720 descricoes
BERT: 157,600/178,720 descricoes
BERT: 158,400/178,720 descricoes
BERT: 159,200/178,720 descricoes
BERT: 160,000/178,720 descricoes
BERT: 160,800/178,720 descricoes
BERT: 161,600/178,720 descricoes
BERT: 162,400/178,720 descricoes
BERT: 163,200/178,720 descricoes
BERT: 164,000/178,720 descricoes
BERT: 164,800/178,720 descricoes
BERT: 165,600/178,720 descricoes
BERT: 166,400/178,720 descricoes
BERT: 167,200/178,720 descricoes
BERT: 168,000/178,720 descricoes
BERT: 168,800/178,720 descricoes
BERT: 169,600/178,720 descricoes
BERT: 170,400/178,720 descricoes
BERT: 171,200/178,720 descricoes
BERT: 172,000/178,720 descricoes
BERT: 172,800/178,720 descricoes
BERT: 173,600/178,720 descricoes
BERT: 174,400/178,720 descricoes
BERT: 175,200/178,720 descricoes
BERT: 176,000/178,720 descricoes
BERT: 176,800/178,720 descricoes
BERT: 177,600/178,720 descricoes
BERT: 178,400/178,720 descricoes
BERT: 178,720/178,720 descricoes
Formato da matriz BERT: (178720, 768)

# Busca

In [15]:
from sklearn.metrics.pairwise import cosine_similarity


def buscar_top_k(vetor_consulta, matriz_documentos, k=10):
    if not isinstance(k, int) or isinstance(k, bool) or k < 1:
        raise ValueError('k deve ser um inteiro positivo.')
    if matriz_documentos.shape[0] != len(df):
        raise ValueError('As linhas dos embeddings devem corresponder aos jogos de df.')
    vetor_consulta = np.asarray(vetor_consulta).reshape(1, -1)
    if not np.isfinite(vetor_consulta).all() or not np.any(vetor_consulta):
        raise ValueError('A consulta nao possui um vetor valido para busca.')
    similaridades = cosine_similarity(vetor_consulta, matriz_documentos)[0]
    # Vetores nulos nao representam descricoes e ficam fora do ranking.
    validos = np.flatnonzero(np.any(matriz_documentos != 0, axis=1))
    indices = validos[np.argsort(-similaridades[validos], kind='stable')[:k]]
    resultado = df.iloc[indices][['appid', 'name', 'genres', 'description']].copy()
    resultado.insert(0, 'posicao', range(1, len(resultado) + 1))
    resultado['similaridade'] = similaridades[indices]
    resultado['pagina_steam'] = 'https://store.steampowered.com/app/' + resultado['appid'].astype(str)
    return resultado

In [16]:
def representar_consulta_word2vec(
    texto
):
    tokens = tokenizar(texto)
    tokens = normalizar(tokens)
    tokens = remover_stopwords(tokens)

    conhecidos = [
        token
        for token in tokens
        if token in modelo_w2v.wv
    ]

    oov = [
        token
        for token in tokens
        if token not in modelo_w2v.wv
    ]

    if not conhecidos:
        return None, conhecidos, oov

    vetor = np.mean(
        [
            modelo_w2v.wv[token]
            for token in conhecidos
        ],
        axis=0
    )

    return vetor, conhecidos, oov

In [17]:
def representar_consulta_bert(
    texto
):
    return gerar_embeddings_bert(
        [texto]
    )[0]

# Consultar jogos Steam

Execute as representacoes acima e altere a consulta em ingles. Cada modelo compara uma consulta com o catalogo, sem criar uma matriz de todos os pares.

In [18]:
consulta = 'Explore an open world and build a base to survive with friends'
top_k = 10
if not consulta.strip():
    raise ValueError('Digite uma consulta em ingles.')

vetor_w2v, conhecidos, desconhecidos = representar_consulta_word2vec(consulta)
print('Consulta:', consulta)
print('Word2Vec - termos conhecidos:', conhecidos)
print('Word2Vec - termos fora do vocabulario:', desconhecidos)
if vetor_w2v is None:
    print('Word2Vec: nenhum termo conhecido. Tente outras palavras em ingles.')
else:
    resultados_word2vec = buscar_top_k(vetor_w2v, embeddings_word2vec, k=top_k)
    display(resultados_word2vec)

print('Resultados BERT:')
vetor_bert = representar_consulta_bert(consulta)
resultados_bert = buscar_top_k(vetor_bert, embeddings_bert, k=top_k)
display(resultados_bert)

Consulta: Explore an open world and build a base to survive with friends
Word2Vec - termos conhecidos: ['explore', 'open', 'world', 'build', 'base', 'survive', 'friends']
Word2Vec - termos fora do vocabulario: []

,posicao,appid,name,genres,description,similaridade,pagina_steam
69133,1,2141620,Landiscape,Action; Adventure; Indie; Strategy; Free To Play,Landiscape is a relaxed 1 4 player open world ...,0.939624,https://store.steampowered.com/app/2141620
14463,2,655780,Project 5: Sightseer,Action; Adventure; Indie; RPG,Open world multiplayer sandbox RPG game Explor...,0.937014,https://store.steampowered.com/app/655780
117378,3,3435890,Isle of Survival: The New Dawn,Action; Adventure; RPG,Survive and rebuild on a mysterious island Exp...,0.936602,https://store.steampowered.com/app/3435890
75663,4,2313330,TerraTech Worlds,Action; Adventure; Indie; Simulation; Strategy...,TerraTech Worlds is an open world build craft ...,0.933403,https://store.steampowered.com/app/2313330
96253,5,2868100,Shamania,Action; Adventure; RPG,Shamania is an open world survival game where ...,0.933188,https://store.steampowered.com/app/2868100
157209,6,4562650,Island of the Lost,Action; Adventure; Casual; Indie; Simulation,Survive on a mysterious island gather resource...,0.932924,https://store.steampowered.com/app/4562650
39331,7,1337910,Dead Earth Zombies,Action; Adventure; Casual; Indie; RPG; Strateg...,Dead Earth is an open world survival game choo...,0.932216,https://store.steampowered.com/app/1337910
16853,8,717790,Hold Your Own,Action; Adventure; Casual; Indie; Simulation; ...,A single player open world sandbox crafting an...,0.931480,https://store.steampowered.com/app/717790
57190,9,1805750,First Men´s Life,Adventure; Casual; Indie,Create your own world Build fight farm and exp...,0.928565,https://store.steampowered.com/app/1805750
133736,10,3891900,FLINT,Massively Multiplayer,Multiplayer survival in an open world Build yo...,0.928546,https://store.steampowered.com/app/3891900

Resultados BERT:
BERT: 1/1 descricoes

,posicao,appid,name,genres,description,similaridade,pagina_steam
157209,1,4562650,Island of the Lost,Action; Adventure; Casual; Indie; Simulation,Survive on a mysterious island gather resource...,0.857490,https://store.steampowered.com/app/4562650
57190,2,1805750,First Men´s Life,Adventure; Casual; Indie,Create your own world Build fight farm and exp...,0.854418,https://store.steampowered.com/app/1805750
32007,3,1141030,Last Message,Adventure; Casual; Simulation; Free To Play,Use an in game computer to chat with friends t...,0.853731,https://store.steampowered.com/app/1141030
58419,4,1837280,Lost Island,Adventure; Indie; Simulation,Trapped on an Island Find items to survive and...,0.851760,https://store.steampowered.com/app/1837280
59179,5,1857520,Team Ice Cream VR,Casual; Indie; Simulation,Play alone in VR or get together with a friend...,0.848383,https://store.steampowered.com/app/1857520
88691,6,2660460,Aviassembly,Simulation; Early Access,Build and fly your own airplane Complete missi...,0.845177,https://store.steampowered.com/app/2660460
28480,7,1047920,White Sun,RPG,An RPG about surviving a dangerous world with ...,0.845138,https://store.steampowered.com/app/1047920
87857,8,2638240,Escape to the Italian brainrot,Action; Casual; Indie,Explore a strange village filled with Italian ...,0.842539,https://store.steampowered.com/app/2638240
47559,9,1551700,Fractium,Action; Adventure; Strategy,Conquer build and raid in a massive open world...,0.842072,https://store.steampowered.com/app/1551700
74663,10,2286240,Polyturned,Action; Adventure; Indie; Massively Multiplaye...,Your goal is to survive in a city overrun by z...,0.841792,https://store.steampowered.com/app/2286240